# Generated by Django 4.0.5 on 2022-07-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('player', models.ManyToManyField(blank=True, related_name='players', to='api.userprofile')),
            ],
        ),
    ]
