# Generated by Django 4.0.5 on 2022-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_highscore_player_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="winner_combination",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="winning_combinations",
            field=models.JSONField(null=True),
        ),
    ]
