# Generated by Django 4.0.5 on 2022-07-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_highscore_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highscores', to='api.userprofile'),
        ),
    ]
